// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoibxmdy1aY4zyhiujD_oXgAQLVeW16E0',
    appId: '1:448935747682:web:6c9569590e0751796ff13b',
    messagingSenderId: '448935747682',
    projectId: 'todoapp-ffab9',
    authDomain: 'todoapp-ffab9.firebaseapp.com',
    storageBucket: 'todoapp-ffab9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV-bLTcspmMeCchOkVDwOU3nAPDllIpSw',
    appId: '1:448935747682:android:d2c7ba947e5a22806ff13b',
    messagingSenderId: '448935747682',
    projectId: 'todoapp-ffab9',
    storageBucket: 'todoapp-ffab9.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoibxmdy1aY4zyhiujD_oXgAQLVeW16E0',
    appId: '1:448935747682:web:c9e7e2dc80b09b266ff13b',
    messagingSenderId: '448935747682',
    projectId: 'todoapp-ffab9',
    authDomain: 'todoapp-ffab9.firebaseapp.com',
    storageBucket: 'todoapp-ffab9.appspot.com',
  );
}
